---
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - python3-pandas
    - python3-xlrd
    - python3-pip

- name: Install pip modules
  pip: name=influxdb executable=pip3

- name: Patch xlrd
  patch: dest=/usr/lib/python3.4/site-packages/xlrd/compdoc.py src=compdoc.patch

- name: Install import.py script
  copy: src=../../../../import.py dest=/usr/local/bin/import.py mode=755
