- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: rluta
    instance_type: t2.nano
    security_group: proxy-access
    subnet: subnet-6c8e3447
    image: ami-5afe714d
    region: us-east-1
    zone: us-east-1a
    public_ip: 52.21.145.40
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet }}"
         zone: "{{ zone }}"
         assign_public_ip: yes
         instance_tags:
           class: proxy
         wait: true
      register: ec2
    - name: Assign static public IP
      ec2_eip: device_id={{ item.id }} public_ip={{ public_ip }}
      with_items: ec2.instances
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=proxy
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Install credentials
  hosts: proxy
  user: ubuntu
  become: true
  gather_facts: true
  vars:
    config: aws_config
  tasks:
    - name: Install remote aws config
      copy: src={{ aws_config }} dest=/root/.aws owner=root group=root
    - name: Install certificate key
      copy: src=certs/gadatalab.key dest=/etc/nginx/certs/ owner=root group=root mode=400
    - name: Generate up-to-date signing key
      shell: /usr/local/bin/refresh_keys
    - name: Reload nginx
      service: name=nginx state=reloaded
